<?php

namespace AppBundle\Repository;

/**
 * Empresas_categoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Empresas_categoriasRepository extends \Doctrine\ORM\EntityRepository
{
}
