# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders :
        AppBundle\Entity\Usuario:
            algorithm : bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity:
                class : AppBundle:Usuario
                property : email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            logout:
                path: /logout
                target: /

    access_control:
        #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: /.*, roles: ROLE_USER }
